spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0.0
    baseline-description: "Initial version"
  session:
    store-type: redis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.101:3306/gulimail_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  rabbitmq:
    host: 192.168.10.101
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
              acknowledge-mode: manual
  thymeleaf:
    mode: HTML
    cache: false
    check-template-location: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
  data:
    redis:
      host: 192.168.10.101
      port: 6379
gulimail:
  order:
    session:
      secure: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
logging:
  level:
    com.lg.gulimail: debug
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://192.168.10.101:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

xxl:
  job:
    admin:
      addresses: http://192.168.10.101:8080/xxl-job-admin
    accessToken: default_token
    executor:
      appname: gulimail-order-executor
      port: 9997
      logpath: ./logs/xxl-job/gulimail-order
      logretentiondays: 30

seata:
  tx-service-group: gulimail-order-tx-group
  service:
    vgroup-mapping:
      gulimail-order-tx-group: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server

