spring:
  rabbitmq:
    host: 192.168.10.101
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
  cloud:
    sentinel:
      transport:
        # 1. 指定 Sentinel 控制台的地址（你启动控制台 Jar 包的那个地址）
        dashboard: localhost:8333
        # 2. 与控制台交互的端口，如果被占用会自动 +1 探测
        port: 8719
feign:
  sentinel:
    enabled: true
management:
  zipkin:
    tracing:
      # 错误写法：http://localhost:9411/api/v2/spans
      # 正确写法：改成你 Linux 服务器的真实 IP
      endpoint: http://192.168.10.101:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0  # 确保 100% 采样，方便调试