spring:
  application:
    name: gulimail-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
  data:
    redis:
          host: 192.168.10.101
          port: 6379
  rabbitmq:
    host: 192.168.10.101
    port: 5672
server:
  port: 31000
gulimail:
  cart:
    session:
      secure: false
    thread:
      core-size: 16
      max-size: 64
      keep-alive-seconds: 30
      queue-capacity: 2000
logging:
  level:
    com.lg.gulimail: debug
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://192.168.10.101:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
