spring:
  data:
    redis:
      host: 192.168.10.101
      port: 6379
logging:
  level:
    com.lg.gulimail: debug
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://192.168.10.101:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
gulimail:
  auth:
    session:
      secure: false
    login-page-url: http://auth.gulimail.com/login.html
    login-success-redirect: http://gulimail.com
    oauth:
      github:
        authorize-url: https://github.com/login/oauth/authorize
        access-token-url: https://github.com/login/oauth/access_token
        client-id: ${GITHUB_CLIENT_ID:}
        client-secret: ${GITHUB_CLIENT_SECRET:}
        redirect-uri: http://auth.gulimail.com/oauth2.0/github/success
