spring:
  flyway:
    enabled: false
  application:
    name: gulimail-ai
  config:
    import:
      - optional:nacos:gulimail-ai.yaml?server-addr=127.0.0.1:8848&namespace=60506194-2d6f-4685-82e7-a57b9bd9000c&refreshEnabled=true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  data:
    redis:
      host: 192.168.10.101
      port: 6379

  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.10.101:3306/gulimail_ai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 14000

feign:
  sentinel:
    enabled: true # 开启 Feign 对 Sentinel 的支持

logging:
  level:
    com.lg.gulimail: debug
  pattern:
    level: "%5p [${spring.application.name:-},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.10.101:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
